# Pytorch fundamentals

In [6]:
import torch

In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
#retrieve number from tensor
scalar.item()

7

In [10]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
#can tell num of dims a tensor has by num of square brackets on outside 
#only need to count one side
vector.ndim

1

In [12]:
#shape tells how elements inside are arranged
vector.shape

torch.Size([2])

In [13]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.ndim

3

In [18]:
tensor.shape

torch.Size([1, 3, 3])

In [19]:
#^^ dimensions go outer to inner
#"1 dimension of 3 by 3"
#scalars/vectors usually lowercase, matrices/tensors usually uppercase

Random tensors & zeros/ones

In [20]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.0079, 0.4129, 0.6809, 0.0146],
         [0.1012, 0.1376, 0.7790, 0.0428],
         [0.2318, 0.8643, 0.7714, 0.4682]]),
 torch.float32,
 torch.Size([3, 4]))

In [21]:
random_tensor2 = torch.rand(size=(224, 224, 3))
random_tensor2.shape, random_tensor2.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 2)

In [23]:
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

creating a range and tensors like

In [24]:
#torch.arange(start, end, step)
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#one tensor of a certain type with same shape as another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_ones = torch.ones_like(zero_to_ten)
ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

tensor datatypes

Most common is torch.float32 or torch.float

In [26]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [27]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Getting info from tensors

In [28]:
#3 most common attributes: shape, dtype, device
# Create a tensor
some_tensor = torch.rand(3, 4)
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0784, 0.1066, 0.3750, 0.4063],
        [0.3890, 0.5791, 0.0292, 0.5548],
        [0.3411, 0.7492, 0.4663, 0.8057]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Basic operations

In [29]:
x = torch.tensor([1,2,3])
x+10

tensor([11, 12, 13])

In [30]:
x*10

tensor([10, 20, 30])

In [31]:
#^^values inside tensor dont change unless reassigned
x

tensor([1, 2, 3])

In [32]:
x = x-10
x

tensor([-9, -8, -7])

In [33]:
x=x+10
x

tensor([1, 2, 3])

In [34]:
torch.mul(x, 10) #or .multiply

tensor([10, 20, 30])

In [35]:
#more common to use operator symbols
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(x, "*", x)
print("Equals:", x * x)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Matrix multiplication
- inner dimensions must match, resulting shape has outer dimensions

In [36]:
x

tensor([1, 2, 3])

In [37]:
x*x

tensor([1, 4, 9])

In [38]:
torch.matmul(x,x)

tensor(14)

Dealing with matrix shapesose

In [39]:
#torch.transpose(input, dim0, dim1) 
    #input: tensor to transpose, and dim0 and dim1 are the dimensions to be swapped
#tensor.T - where tensor is the desired tensor to transpose
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [40]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [41]:
torch.mm(tensor_A, tensor_B.T) #mm shortcut for matmul

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Aggregation

In [42]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#torch.mean() requires tensors to be float32
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [44]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

Positional min/max

In [45]:
tensor = torch.arange(10,100,10)
print(tensor)

print(f"index of max value: {tensor.argmax()}")
print(f"index of min value: {tensor.argmin()}")

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
index of max value: 8
index of min value: 0


Change tensor datatype

In [46]:
tensor.dtype

torch.int64

In [47]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [48]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Reshaping, stacking, squeezing, unsqueezing

- torch.reshape(input, shape) -reshapes input to shape
- tensor.view(shape) -returns view of orig tensor in different shape
- torch.stack(tensors, dim=0) -concats sequence of tensors along new dimension dim, all tensors must be same size
- torch.squeeze(input) -squeezes input to remove all dims with value 1
- torch.unsqueeze(input, dim) -returns input with dimension value of 1 added at dim
- torch.permute(input, dims) -returns a view of orig input with dimensions permuted to dims

In [49]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [50]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [51]:
z = x.view(1, 7)
z, z.shape
#changing view of tensor with .view() changes original tensor too

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [52]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [53]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [54]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [55]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
#permuting returns a view

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Indexing

In [56]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
#indexing goes outer dim--> inner dim
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][1]}") 
print(f"Third square bracket: {x[0][1][2]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([4, 5, 6])
Third square bracket: 6


In [58]:
#can also use : to specify all vals in this dim, then comma to add another dim
x[:, 0]

tensor([[1, 2, 3]])

In [59]:
x[:,:,2]

tensor([[3, 6, 9]])

In [60]:
x[:,1,2]

tensor([6])

Pytorch tensors and numpy

- torch.from_numpy(ndarray) -np array->pytorch tensor
- torch.tensor.numpy() -pytorch tensor->np array

In [61]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
#np arrays created with dtype float64 by default

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
tensor = torch.from_numpy(array).type(torch.float32)

In [63]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [64]:
# tensor to np array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [65]:
# change the tensor, array stays the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility

In [66]:
#create random tensors with same values (still contain random values but of the same flavor)
import random
#set the random seed
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# have to reset the seed every time a new rand() is called 
#or else tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Running on gpu

In [67]:
torch.cuda.is_available()

True

In [68]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [69]:
# Count number of devices
torch.cuda.device_count()

1

In [70]:
# create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [72]:
#copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [73]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')