In [1]:
import torch

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#retrieve number from tensor
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
#can tell num of dims a tensor has by num of square brackets on outside 
#only need to count one side
vector.ndim

1

In [7]:
#shape tells how elements inside are arranged
vector.shape

torch.Size([2])

In [8]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
#tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
#^^ dimensions go outer to inner
#"1 dimension of 3 by 3"
#scalars/vectors usually lowercase, matrices/tensors usually uppercase

Random tensors & zeros/ones

In [15]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[0.2814, 0.3394, 0.6553, 0.2560],
         [0.2527, 0.4480, 0.4386, 0.0014],
         [0.0703, 0.8823, 0.1190, 0.8839]]),
 torch.float32,
 torch.Size([3, 4]))

In [16]:
random_tensor2 = torch.rand(size=(224, 224, 3))
random_tensor2.shape, random_tensor2.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 2)

In [18]:
ones = torch.ones(size=(3,4))
ones, ones.dtype, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

creating a range and tensors like

In [19]:
#torch.arange(start, end, step)
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#one tensor of a certain type with same shape as another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_ones = torch.ones_like(zero_to_ten)
ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

tensor datatypes

Most common is torch.float32 or torch.float

In [21]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

Getting info from tensors

In [23]:
#3 most common attributes: shape, dtype, device
# Create a tensor
some_tensor = torch.rand(3, 4)
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6778, 0.8401, 0.5327, 0.1145],
        [0.3362, 0.2734, 0.9131, 0.6776],
        [0.1624, 0.7543, 0.1284, 0.4526]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Basic operations

In [24]:
x = torch.tensor([1,2,3])
x+10

tensor([11, 12, 13])

In [25]:
x*10

tensor([10, 20, 30])

In [26]:
#^^values inside tensor dont change unless reassigned
x

tensor([1, 2, 3])

In [27]:
x = x-10
x

tensor([-9, -8, -7])

In [28]:
x=x+10
x

tensor([1, 2, 3])

In [29]:
torch.mul(x, 10) #or .multiply

tensor([10, 20, 30])

In [30]:
#more common to use operator symbols
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(x, "*", x)
print("Equals:", x * x)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Matrix multiplication
- inner dimensions must match, resulting shape has outer dimensions

In [31]:
x

tensor([1, 2, 3])

In [32]:
x*x

tensor([1, 4, 9])

In [33]:
torch.matmul(x,x)

tensor(14)

Dealing with matrix shapesose

In [34]:
#torch.transpose(input, dim0, dim1) 
    #input: tensor to transpose, and dim0 and dim1 are the dimensions to be swapped
#tensor.T - where tensor is the desired tensor to transpose
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [35]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [36]:
torch.mm(tensor_A, tensor_B.T) #mm shortcut for matmul

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Aggregation

In [43]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#torch.mean() requires tensors to be float32
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [48]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

Positional min/max